<?php

use Illuminate\Database\Seeder;

class PaisesSeeder extends Seeder
{
    
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['170', 'COLOMBIA'],
            ['004', 'AFGANISTAN'],
            ['008', 'ALBÀNIA'],
            ['012', 'ALGÈRIA'],
            ['016', 'SAMOA AMERICANA'],
            ['020', 'ANDORRA'],
            ['024', 'ANGOLA'],
            ['028', 'ANTIGUA I BARBUDA'],
            ['031', 'AZERBAIDJAN'],
            ['032', 'ARGENTINA'],
            ['036', 'AUSTRÀLIA'],
            ['040', 'ÀUSTRIA'],
            ['044', 'BAHAMES'],
            ['048', 'BAHRAIN'],
            ['050', 'BANGLA DESH'],
            ['051', 'ARMÈNIA'],
            ['052', 'BARBADOS'],
            ['056', 'BÈLGICA'],
            ['060', 'BERMUDES, LES'],
            ['064', 'BHUTAN'],
            ['068', 'BOLÍVIA'],
            ['070', 'BÒSNIA I HERCEGOVINA'],
            ['072', 'BOTSWANA'],
            ['076', 'BRASIL'],
            ['084', 'BELIZE'],
            ['090', 'SALOMÓ'],
            ['092', 'VERGES, ILLES (REGNE UNIT)'],
            ['096', 'BRUNEI'],
            ['100', 'BULGÀRIA'],
            ['104', 'MYANMAR'],
            ['108', 'BURUNDI'],
            ['112', 'BIELORÚSSIA'],
            ['116', 'CAMBODJA'],
            ['120', 'CAMERUN'],
            ['124', 'CANADÀ'],
            ['132', 'CAP VERD'],
            ['136', 'CAIMAN, LES'],
            ['140', 'CENTREAFRICANA, REPÚBLICA'],
            ['144', 'SRI LANKA'],
            ['148', 'TXAD'],
            ['152', 'XILE'],
            ['156', 'XINA'],
            ['158', 'TAIWAN'],
            ['174', 'COMORES'],
            ['175', 'MAYOTTE(FRANÇA)'],
            ['178', 'CONGO'],
            ['180', 'CONGO, REPÚBLICA DEMOCRÀTICA DEL'],
            ['184', 'COOK, ILLES'],
            ['188', 'COSTA RICA'],
            ['191', 'CROÀCIA'],
            ['192', 'CUBA'],
            ['196', 'XIPRE'],
            ['203', 'TXECA, REPÚBLICA'],
            ['204', 'BENÍN'],
            ['208', 'DINAMARCA'],
            ['212', 'DOMINICA'],
            ['214', 'DOMINICANA, REPÚBLICA'],
            ['218', 'EQUADOR'],
            ['222', 'SALVADOR, EL'],
            ['226', 'GUINEA EQUATORIAL'],
            ['231', 'ETIÒPIA'],
            ['232', 'ERITREA'],
            ['233', 'ESTÒNIA'],
            ['234', 'FÈROE, ILLES'],
            ['238', 'MALVINES, ILLES'],
            ['242', 'FIJI'],
            ['246', 'FINLÀNDIA'],
            ['248', 'ALAND, ILLES (FINLÀNDIA)'],
            ['250', 'FRANÇA'],
            ['254', 'GUAIANA FRANCESA, LA'],
            ['258', 'POLINÈSIA FRANCESA'],
            ['262', 'DJIBOUTI'],
            ['266', 'GABON'],
            ['268', 'GEÒRGIA'],
            ['270', 'GÀMBIA'],
            ['275', 'CISJORDÀNIA I GAZA'],
            ['276', 'ALEMANYA'],
            ['288', 'GHANA'],
            ['292', 'GIBRALTAR'],
            ['296', 'KIRIBATI'],
            ['300', 'GRÈCIA'],
            ['304', 'GRENLÀNDIA'],
            ['308', 'GRENADA'],
            ['312', 'GUADELOUPE'],
            ['316', 'GUAM'],
            ['320', 'GUATEMALA'],
            ['324', 'GUINEA'],
            ['328', 'GUYANA'],
            ['332', 'HAITÍ'],
            ['336', 'VATICÀ'],
            ['340', 'HONDURES'],
            ['344', 'HONG KONG'],
            ['348', 'HONGRIA'],
            ['352', 'ISLÀNDIA'],
            ['356', 'ÍNDIA'],
            ['360', 'INDONÈSIA'],
            ['364', 'IRAN'],
            ['368', 'IRAQ'],
            ['372', 'IRLANDA'],
            ['376', 'ISRAEL'],
            ['380', 'ITÀLIA'],
            ['384', "COSTA D'IVORI"],
            ['388', 'JAMAICA'],
            ['392', 'JAPÓ'],
            ['398', 'KAZAKHSTAN'],
            ['400', 'JORDÀNIA'],
            ['404', 'KENYA'],
            ['408', 'COREA, REPÚBLICA DEMOCRÀTICA POPULAR DE'],
            ['410', 'COREA, REPÚBLICA DE'],
            ['414', 'KUWAIT'],
            ['417', 'KIRGUIZISTAN'],
            ['418', 'LAOS'],
            ['422', 'LÍBAN'],
            ['426', 'LESOTHO'],
            ['428', 'LETÒNIA'],
            ['430', 'LIBÈRIA'],
            ['434', 'LÍBIA'],
            ['438', 'LIECHTENSTEIN'],
            ['440', 'LITUÀNIA'],
            ['442', 'LUXEMBURG'],
            ['446', 'MACAU'],
            ['450', 'MADAGASCAR'],
            ['454', 'MALAWI'],
            ['458', 'MALÀISIA'],
            ['462', 'MALDIVES'],
            ['466', 'MALI'],
            ['470', 'MALTA'],
            ['474', 'MARTINICA'],
            ['478', 'MAURITÀNIA'],
            ['480', 'MAURICI'],
            ['484', 'MÈXIC'],
            ['492', 'MÒNACO'],
            ['496', 'MONGÒLIA'],
            ['498', 'MOLDÀVIA'],
            ['499', 'MONTENEGRO'],
            ['500', 'MONTSERRAT'],
            ['504', 'MARROC'],
            ['508', 'MOÇAMBIC'],
            ['512', 'OMAN'],
            ['516', 'NAMÍBIA'],
            ['520', 'NAURU'],
            ['524', 'NEPAL'],
            ['528', 'PAÏSOS BAIXOS'],
            ['530', 'ANTILLES NEERLANDESES'],
            ['533', 'ARUBA'],
            ['540', 'NOVA CALEDÒNIA'],
            ['548', 'VANUATU'],
            ['554', 'NOVA ZELANDA'],
            ['558', 'NICARAGUA'],
            ['562', 'NÍGER'],
            ['566', 'NIGÈRIA'],
            ['570', 'NIUE'],
            ['574', 'NORFOLK, ILLA'],
            ['578', 'NORUEGA'],
            ['580', 'MARIANNES DEL NORD, ILLES'],
            ['583', 'MICRONÈSIA, ESTATS FEDERATS DE'],
            ['584', 'MARSHALL'],
            ['585', 'PALAU'],
            ['586', 'PAKISTAN'],
            ['591', 'PANAMÀ'],
            ['598', 'PAPUA NOVA GUINEA'],
            ['600', 'PARAGUAI'],
            ['604', 'PERÚ'],
            ['608', 'FILIPINES'],
            ['612', 'PITCAIRN'],
            ['616', 'POLÒNIA'],
            ['620', 'PORTUGAL'],
            ['624', 'GUINEA BISSAU'],
            ['626', 'TIMOR ORIENTAL'],
            ['630', 'PUERTO RICO'],
            ['634', 'QATAR'],
            ['638', 'REUNIÓ, ILLA DE LA'],
            ['642', 'ROMANIA'],
            ['643', 'RÚSSIA'],
            ['646', 'RWANDA'],
            ['654', 'SANTA HELENA'],
            ['659', 'SAINT CHRISTOPHER I NEVIS'],
            ['660', 'ANGUILLA'],
            ['662', 'SAINT LUCIA'],
            ['666', 'SAINT-PIERRE-ET-MIQUELON'],
            ['670', 'SAINT VINCENT I LES GRENADINES'],
            ['674', 'SAN MARINO'],
            ['678', 'SAO TOMÉ I PRÍNCIPE'],
            ['682', 'ARÀBIA SAUDITA'],
            ['686', 'SENEGAL'],
            ['688', 'SÈRBIA'],
            ['690', 'SEYCHELLES'],
            ['694', 'SIERRA LEONE'],
            ['702', 'SINGAPUR'],
            ['703', 'ESLOVÀQUIA'],
            ['704', 'VIETNAM'],
            ['705', 'ESLOVÈNIA'],
            ['706', 'SOMÀLIA'],
            ['710', 'SUD-ÀFRICA, REPÚBLICA DE'],
            ['716', 'ZIMBABWE'],
            ['724', 'ESPANYA'],
            ['732', 'SÀHARA OCCIDENTAL'],
            ['736', 'SUDAN'],
            ['740', 'SURINAM'],
            ['744', 'SVALBARD'],
            ['748', 'SWAZILÀNDIA'],
            ['752', 'SUÈCIA'],
            ['756', 'SUÏSSA'],
            ['760', 'SÍRIA'],
            ['762', 'TADJIKISTAN'],
            ['764', 'TAILÀNDIA'],
            ['768', 'TOGO'],
            ['772', 'TOKELAU'],
            ['776', 'TONGA'],
            ['780', 'TRINITAT I TOBAGO'],
            ['784', 'UNIÓ DELS EMIRATS ÀRABS'],
            ['788', 'TUNÍSIA'],
            ['792', 'TURQUIA'],
            ['795', 'TURKMENISTAN'],
            ['796', 'TURKS I CAICOS, ILLES'],
            ['798', 'TUVALU'],
            ['800', 'UGANDA'],
            ['804', 'UCRAÏNA'],
            ['807', 'MACEDÒNIA'],
            ['818', 'EGIPTE'],
            ['826', 'REGNE UNIT'],
            ['830', 'ANGLONORMANDES, ILLES'],
            ['831', 'GUERNSEY (REGNE UNIT)'],
            ['832', 'JERSEY (REGNE UNIT)'],
            ['833', 'MAN, ILLA DE'],
            ['834', 'TANZÀNIA'],
            ['840', "ESTATS UNITS D'AMÈRICA"],
            ['850', "VERGES, ILLES (ESTATS UNITS D'AMÈRICA)"],
            ['854', "BURKINA FASO"],
            ['858', "URUGUAI"],
            ['860', "UZBEKISTAN"],
            ['862', "VENEÇUELA"],
            ['876', "WALLIS I FUTUNA"],
            ['882', "SAMOA"],
            ['887', "IEMEN"],
            ['891', "IUGOSLÀVIA"],
            ['894', "ZÀMBIA"],
            ['998', "APÀTRIDA"],
            ['ZZ1', "KOSOVO"] 
        ];

        foreach ($paises as $pais)
        {
            DB::table('paises')->insert([
                "nombre" => $pais[1],
                "codigo" => $pais[0]
            ]);
        }


    }
}
